apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-prefer
  name: nginx-prefer
spec:
  containers:
  - image: nginx
    name: nginx-prefer
    resources: {}
  dnsPolicy: ClusterFirst
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: datakey
            operator: In
            values:
            - hhd
