apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: MyApp
  name: myapp-pod
spec:
  containers:
  - image: busybox:1.28
    name: myapp-container
    env:
    - name: name
      value: diyasini
    command :  ['sh', '-c', 'echo The app is running! && sleep 3600']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
