apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  tolerations:   # Tolerations is used to schedule pods on nodes with taints . gpu=true:NoSchedule <key:value:effect> 
  - key: "gnu"   # Taint key
    operator: "Equal" # Taint operator
    value: "true" # Taint value
    effect: "NoSchedule"  # Taint effect  NoSchedule is used to prevent scheduling of pods on nodes with taints
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
