apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
    - name: app
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      image: busybox:latest
      envFrom:
        - configMapRef:
            name: app-cm

