apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: daemonset
  name: daemonset
spec:
  template:
    metadata:
      labels:
        app: daemonset
    spec:
      containers:
      - image: nginx
        name: nginx
  selector:
    matchLabels:
      app: daemonset
